{ config, pkgs, ... }:

let
  docker-compose-completions = pkgs.callPackage ./packages/docker-compose-completions.nix {};
  docx2txt = pkgs.callPackage ./packages/docx2txt.nix {};
  libinput-gestures = pkgs.callPackage ./packages/libinput-gestures/default.nix {};
  miller = pkgs.callPackage ./packages/miller.nix {};
  wsta = pkgs.callPackage ./packages/wsta.nix {};

in {
  environment.systemPackages = with pkgs; [
    #(lowPrio texlive.combined.scheme-full)
    #csvtotable
    #docx2txt
    #go_1_6
    #kitty
    #wsta
    #x_x
    (lowPrio moreutils) # prefer GNU parallel
    acpi
    alacritty
    alsaPlugins
    alsaUtils
    antiword
    aria
    asciinema
    aspell
    aspellDicts.en
    awscli
    azure-cli
    binutils
    bitcoin
    boot
    #chromiumDev
    chromium
    clojure
    cups
    curl
    dateutils
    direnv
    dnsutils
    docker-machine
    docker_compose docker-compose-completions
    dosfstools
    dropbox-cli
    dunst
    enscript
    exiv2
    expect
    ffcast
    ffmpeg
    file
    firefox-devedition-bin
    fzf
    gcolor2
    geoipWithDatabase
    ghc
    ghostscript
    gist
    git
    gitAndTools.hub
    gnumake
    gnupg
    go-pup
    google-cloud-sdk
    google-drive-ocamlfuse
    graphicsmagick
    graphviz
    haskellPackages.xmobar
    highlight
    html2text
    httpie
    httping
    hy
    iftop
    imagemagick
    inkscape
    inotify-tools
    iotop
    jdk
    jo
    jq
    lastpass-cli
    leiningen
    libevent
    libinput-gestures
    libnotify
    libreoffice-fresh
    libxls
    lighttable
    linuxPackages.perf
    lsof
    mailutils
    maim
    mariadb
    mediainfo
    megatools
    miller
    mitmproxy
    mongodb
    mongodb-tools
    mpv
    msmtp
    mupdf
    neomutt
    neovim
    netcat
    nethogs
    netpbm
    ngrep
    nix-prefetch-scripts
    nix-zsh-completions
    nixops
    nmap
    nodejs-8_x
    notmuch
    notmuch-addrlookup
    notmuch-mutt
    ntfs3g
    ocrad
    offlineimap
    openssl
    pandoc
    parallel perlPackages.DBDSQLite
    patchelf
    pciutils
    pdfgrep
    pdftk
    perlPackages.HTMLParser
    pgcli
    pianobar
    ponymix
    poppler_utils
    postgresql
    psmisc
    pv
    python
    python27Packages.setuptools
    python35Packages.pygments
    recode
    redis
    redshift
    remarshal
    ripgrep
    rlwrap
    rofi
    rsync
    ruby
    rxvt_unicode-with-plugins
    scrot
    setroot
    slop
    socat
    sqlite
    sshuttle
    st
    stack
    strace
    sxhkd
    sxiv
    t
    tcpdump
    tdesktop
    telnet
    tesseract
    tmate
    tmux
    torbrowser
    traceroute
    tree
    tsocks
    ttyrec
    units
    unoconv
    unzip
    urlview
    usbutils
    vaapiVdpau
    vimHugeX
    virt-viewer
    w3m
    watchman
    wdiff
    weechat
    wget
    whois
    wmctrl
    xbindkeys
    xclip
    xdg_utils
    xdotool
    xfce.thunar
    xlsx2csv
    xmind
    xml2
    xorg.xev
    xorg.xinput
    xorg.xrandr
    xorg.xset
    xsel
    xurls
    yarn
    youtube-dl
    zathura
    zip
  ];
}
