#!/usr/bin/env bash

controller='A4:34:D9:97:A7:EC'

bt_headset_macs=$(sudo sh -c "grep -l 0000110b-0000-1000-8000-00805f9b34fb /var/lib/bluetooth/$controller/*/info" | cut -d/ -f6)

declare -A sinks
sinks=(
    [earbuds]=bluez_sink.C0_28_8D_25_99_38.a2dp_sink
    [headset]=bluez_sink.04_5D_4B_EA_1D_09.a2dp_sink
    [speakers]=alsa_output.pci-0000_00_1f.3.analog-stereo
)

current_sink=$(pactl list short sinks | awk '/RUNNING/ { print $2 }')


bt-setup() {
    device=$(awk -F. '{ gsub(/_/, ":", $2); print $2 }' <<<$1)

    expect - <<<"
    set prompt \"#\"

    spawn bluetoothctl; expect -re \$prompt

    send \"select $controller\r\"; expect \"Controller\"
    send \"power off\r\"; expect \"succeeded\"; send \"power on\r\"; expect \"succeeded\"

    send \"connect $device\r\"; expect \"successful\"

    send \"quit\r\"
    "

    pactl set-card-profile bluez_card.${device//:/_} a2dp_sink
}


sink=$(
    [[ $1 == toggle ]] &&
        {
            [[ $current_sink == ${sinks[headset]} ]] &&
                echo ${sinks[speakers]} ||
                    echo ${sinks[headset]}
        } ||
            echo ${sinks[$1]}
    )

[[ $sink == bluez* ]] && bt-setup $sink

pactl list short sink-inputs | awk '{ print $1 }' | xargs -i -n1 pactl move-sink-input {} $sink
pactl set-default-sink $sink
