#!/usr/bin/env bash

path=$1

ffmpeg \
    -f alsa -i pulse \
    -f x11grab -video_size %s -i %D+%c \
    -codec:v libvpx -quality good \
    -preset veryfast \
    -cpu-used 0 \
    -crf 18 \
    -pix_fmt yuv420p \
    $path
